from PyQt5 import QtCore, QtGui, QtWidgets
from datetime import date
import pyttsx3


class Ui_Cheque(object):
    def talk(self):
        text = self.lblAmountInWOrdsOut.text()
        engine = pyttsx3.init()
        engine.say(text)
        engine.runAndWait()

    def setupUi(self, Cheque):
        today = date.today()
        todaydate = f"{today}"
        Cheque.setObjectName("Cheque")
        Cheque.resize(906, 537)
        self.centralwidget = QtWidgets.QWidget(Cheque)
        self.centralwidget.setObjectName("centralwidget")
        self.labelName = QtWidgets.QLabel(self.centralwidget)
        self.labelName.setGeometry(QtCore.QRect(150, 175, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelName.setFont(font)
        self.labelName.setObjectName("labelName")
        self.labelAmountInWords = QtWidgets.QLabel(self.centralwidget)
        self.labelAmountInWords.setGeometry(QtCore.QRect(40, 235, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelAmountInWords.setFont(font)
        self.labelAmountInWords.setObjectName("labelAmountInWords")
        self.labelDate = QtWidgets.QLabel(self.centralwidget)
        self.labelDate.setGeometry(QtCore.QRect(630, 60, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelDate.setFont(font)
        self.labelDate.setObjectName("labelDate")
        self.labelTitle = QtWidgets.QLabel(self.centralwidget)
        self.labelTitle.setGeometry(QtCore.QRect(200, 30, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.labelTitle.setFont(font)
        self.labelTitle.setObjectName("labelTitle")
        self.labelKsh = QtWidgets.QLabel(self.centralwidget)
        self.labelKsh.setGeometry(QtCore.QRect(640, 110, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelKsh.setFont(font)
        self.labelKsh.setObjectName("labelKsh")
        self.labelSign = QtWidgets.QLabel(self.centralwidget)
        self.labelSign.setGeometry(QtCore.QRect(520, 405, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelSign.setFont(font)
        self.labelSign.setObjectName("labelSign")
        self.labelChequeNo = QtWidgets.QLabel(self.centralwidget)
        self.labelChequeNo.setGeometry(QtCore.QRect(570, 10, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelChequeNo.setFont(font)
        self.labelChequeNo.setObjectName("labelChequeNo")
        self.pushButtonClose = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonClose.setGeometry(QtCore.QRect(410, 460, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonClose.setFont(font)
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.pushButtonClose.clicked.connect(Cheque.close)
        self.labelAccountNumber = QtWidgets.QLabel(self.centralwidget)
        self.labelAccountNumber.setGeometry(QtCore.QRect(40, 295, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelAccountNumber.setFont(font)
        self.labelAccountNumber.setObjectName("labelAccountNumber")
        self.labelPayToOut = QtWidgets.QLabel(self.centralwidget)
        self.labelPayToOut.setGeometry(QtCore.QRect(190, 180, 521, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.labelPayToOut.setFont(font)
        self.labelPayToOut.setAutoFillBackground(True)
        self.labelPayToOut.setObjectName("labelPayToOut")
        self.lblAmountInWOrdsOut = QtWidgets.QLabel(self.centralwidget)
        self.lblAmountInWOrdsOut.setGeometry(QtCore.QRect(190, 240, 521, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lblAmountInWOrdsOut.setFont(font)
        self.lblAmountInWOrdsOut.setAutoFillBackground(True)
        self.lblAmountInWOrdsOut.setObjectName("lblAmountInWOrdsOut")
        self.lblAcctNoOut = QtWidgets.QLabel(self.centralwidget)
        self.lblAcctNoOut.setGeometry(QtCore.QRect(190, 300, 521, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lblAcctNoOut.setFont(font)
        self.lblAcctNoOut.setAutoFillBackground(True)
        self.lblAcctNoOut.setObjectName("lblAcctNoOut")
        self.lblSignOut = QtWidgets.QLabel(self.centralwidget)
        self.lblSignOut.setGeometry(QtCore.QRect(570, 410, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lblSignOut.setFont(font)
        self.lblSignOut.setAutoFillBackground(True)
        self.lblSignOut.setObjectName("lblSignOut")
        self.lblKshOut = QtWidgets.QLabel(self.centralwidget)
        self.lblKshOut.setGeometry(QtCore.QRect(690, 115, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lblKshOut.setFont(font)
        self.lblKshOut.setAutoFillBackground(True)
        self.lblKshOut.setObjectName("lblKshOut")
        self.lblDateOut = QtWidgets.QLabel(self.centralwidget)
        self.lblDateOut.setGeometry(QtCore.QRect(680, 65, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lblDateOut.setFont(font)
        self.lblDateOut.setAutoFillBackground(True)
        self.lblDateOut.setText(todaydate)
        self.lblDateOut.setObjectName("lblDateOut")
        self.lblChequeNoOut = QtWidgets.QLabel(self.centralwidget)
        self.lblChequeNoOut.setGeometry(QtCore.QRect(680, 15, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lblChequeNoOut.setFont(font)
        self.lblChequeNoOut.setAutoFillBackground(True)
        self.lblChequeNoOut.setObjectName("lblChequeNoOut")
        self.pushButtonTalk = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.talk())
        self.pushButtonTalk.setGeometry(QtCore.QRect(270, 460, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonTalk.setFont(font)
        self.pushButtonTalk.setObjectName("pushButtonTalk")
        Cheque.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Cheque)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 906, 21))
        self.menubar.setObjectName("menubar")
        Cheque.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Cheque)
        self.statusbar.setObjectName("statusbar")
        Cheque.setStatusBar(self.statusbar)

        self.retranslateUi(Cheque)
        QtCore.QMetaObject.connectSlotsByName(Cheque)

    def retranslateUi(self, Cheque):
        _translate = QtCore.QCoreApplication.translate
        Cheque.setWindowTitle(_translate("Cheque", "MainWindow"))
        self.labelName.setText(_translate("Cheque", "Pay:"))
        self.labelAmountInWords.setText(_translate("Cheque", "Amount in words:"))
        self.labelDate.setText(_translate("Cheque", "Date:"))
        self.labelTitle.setText(_translate("Cheque", "MONEY BANK"))
        self.labelKsh.setText(_translate("Cheque", "Ksh:"))
        self.labelSign.setText(_translate("Cheque", "Sign:"))
        self.labelChequeNo.setText(_translate("Cheque", "Cheque NO:"))
        self.pushButtonClose.setText(_translate("Cheque", "Close"))
        self.labelAccountNumber.setText(_translate("Cheque", "Account number:"))
        self.pushButtonTalk.setText(_translate("Cheque", "Talk"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Cheque = QtWidgets.QMainWindow()
    ui = Ui_Cheque()
    ui.setupUi(Cheque)
    Cheque.show()
    sys.exit(app.exec_())
